config/routes.rb
Rails.application.routes.draw do
  root 'core#index'

  post 'search' => 'core#search', as: 'search_question'
  post 'search/autocomplete' => 'core#elastic', as: 'autocomplete'

  namespace :admin do
    get '' => 'panel#index', as: 'panel'
    get 'search/detail/:title' => 'panel#search_detail', as: 'search_detail'
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  settings index: { number_of_shards: 5, number_of_replicas: 0 } do
    mappings dynamic: 'false' do
      indexes :id, type: 'integer'
      indexes :title, type: 'string'
    end
  end

  def as_indexed_json(options = {})
    as_json(only: ['id', 'title'])
  end

  validates :title, :answer, :presence => true

end

app/models/search.rb
class Search < ActiveRecord::Base

  validates :title, :client, :presence => true
end

app/controllers/admin/panel_controller.rb
class Admin::PanelController < ApplicationController
  def index
    @searchs = Search.group(:title).order(count: :desc).count
  end

  def search_detail
    @searchs = Search.where(title: params[:title])
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html, :json

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  config.generators do |g|
    g.factory_girl dir: 'spec/factories'
  end
end

app/controllers/core_controller.rb
class CoreController < ApplicationController
  def index
  end

  def search
    question = Question.find_by(title: search_params[:query])
    @question = QuestionPresenter.new(question, search_params[:query])
    search = IndexerService.process(
      title: search_params[:query],
      client: "Admin",
      address_ip: request.env['REMOTE_ADDR']
    )
  end

  def elastic
    @questions = Question.search(search_params[:query]).results.map do |q|
      q._source.title
    end
    render json: @questions
  end

  private
  def search_params
    params.require(:core).permit(:query)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/core_helper.rb
module CoreHelper
end

app/views/admin/panel/index.html.slim
.container
  .page-header
    h1 Statistics of Search
  .col-md-4
    = content_tag :canvas, nil, id: "chartSearch", :height => 250, data: {info: @searchs}
  .col-md-8
    table.table.table-striped
      th Search
      th Count
      - @searchs.each do |search|
        tr
          td = link_to search[0], admin_search_detail_path(search[0])
          td = search[1]

= javascript_include_tag 'admin/chart'

app/views/admin/panel/search_detail.html.slim
.container
  .page-header
    h1 Search detail

  .col-md-8
    table.table.table-striped
      th Search
      th IP
      th Date
      - @searchs.each do |search|
        tr
          td = search.title
          td = search.address_ip
          td = search.created_at.strftime("%d/%m/%Y at %H:%M")

app/views/core/index.html.slim
.pg-header
  .container
    h1 Can we help you?

    = simple_form_for :core, :url => {:action => :search}, :html => {:autocomplete => "off"} do |f|
      .form-group.col-md-12
        = f.input :query, input_html: { id: 'tags', class: 'input-search' }, :placeholder => "Search", :label => false
      .form-group.col-md-12
        = f.button :submit, "Search", :class => "button-search"
        

app/views/core/search.html.slim
.container
  = render @question.partial, question: @question

app/views/layouts/application.html.slim
doctype html
html
  head
  title Helpjuice
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet"
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

  body
    .page-container
      = render "partials/navbar"
      div class="col-md-12"
          - flash.each do |name, msg|
              = content_tag :div, msg, class: "alert alert-success #{name}"

      div
        == yield

app/views/partials/_navbar.html.slim
nav class="navbar navbar-inverse"
  .container-fluid
    div class="navbar-header"
      a class="navbar-brand" href="/" Knowledge base
    .navbar-collapse.collapse
      ul.nav.navbar-nav.navbar-right
        li
          = link_to "Analytics page", admin_panel_path

app/views/partials/_question_found.html.slim
.page-header
  h1 = @question.title

p = @question.answer

app/views/partials/_question_not_found.slim
.container
  .page-header
    h1 Search results
  ol
    - Question.search(@question.search).records.each do |q|
      li = q.title